# Generated by Django 3.0.2 on 2020-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myown_app', '0002_article_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='content of this post in none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=models.TextField(max_length=1000),
        ),
    ]
