# Generated by Django 3.0.2 on 2020-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myown_app', '0004_auto_20200526_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='listLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
